// LAYOUT
export const LAYOUT_CHANGE = 'LAYOUT_CHANGE';
export const PERPAGE_CHANGE = 'PERPAGE_CHANGE';

// SORTING
export const SORT_CHANGE = 'SORT_CHANGE';

// FILTERING
export const FAVORITES_CHANGE = 'FAVORITES_CHANGE';

// MOVIES
export const ADD_MOVIE = 'ADD_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const MOVIE_TOGGLE_FAVORITE = 'MOVIE_TOGGLE_FAVORITE';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';
export const LOAD_MOVIES = 'LOAD_MOVIES';

// PLAYER
export const PLAY_MOVIE = 'PLAY_MOVIE';
export const STOP_MOVIE = 'STOP_MOVIE';

// PAGINATION
export const PAGE_CHANGE = 'PAGE_CHANGE';
